### ISSUE TITLE
Import existing cameras for vrg gen

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#101]
For larger scale testing of the wrist data- it would be very helpful to be able to load a previous set of cam calibrations as input for the vrg gen

**Comment by vforcesar** [comment]
Additionally, it would be helpful if the calibration and radiograph files updated automatically. Currently, I have to delete these files whenever I modify the cameras.

**Comment by jcfr** [comment]
> very helpful to be able to load a previous set of cam calibrations 

Currently the function `onGenerateVRG`[^1] ends up calling `RadiographGeneration.generateNCameras()` and `IO.generateCameraCalibrationFile()`[^2], to support this, we should skip the generation of the calibration files by allowing the user to select an existing directory with `camN`.json files.

The following UI needs to be updated implementing the following changes:
* Move `# of Possible Cameras` and `Camera offset` up 
* Add radio buttons for toggling between automatic generation vs batch load of possible cameras

**Comment by jcfr** [comment]
Closing. This become obsolete following the integration of commit 7d1de4d (ENH: Hierarchical approach to 3d registration) through pull request #99.
