### ISSUE TITLE
partial volumes - reoriented from expected....

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#103]
relative to the corner coordinate of the partial volume tra.. the model orieantation we've conventionally used is no longer consistent:

| expected: | current: |
|--|--|
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/dfe02bc2-663c-47f4-a93a-f24be80b035d) | ![image (1)](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/65bf3f75-ebf8-4053-96c2-52b5f1b2b869) |

**Comment by jcfr** [comment]
@amymmorton To allow us to more easily reproduce the problem, would it be possible to provide  the steps & input files allowing to reproduce the problem in SlicerAutoscoperM ?

**Comment by amymmorton** [comment]
Same input as #102 (BN00107)

Using Slicer stable 5.6.2 When the partial volumes are generated from the model (converted to segmentations)
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/679960a1-5734-47b3-baf1-4a7b4ba36dc8)


When generated with Slicer 5.7.0, the transform and pvol do appear to be identical

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/b9a89afa-280d-4480-8543-7719737611b1)

perhaps only #102  needs to be addressed- sorry for confusion
