### ISSUE TITLE
Automatic camera placement for 4DCT

### ISSUE THREAD

**Issue by vforcesar** [BrownBiomechanics/SlicerAutoscoperM#105]
Hi, It looks like the automatic camera placement feature doesn't work for my data. It always the error below
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/132497790/729379c5-91dc-46c2-8b18-34ac03bfc32a)

**Comment by NicerNewerCar** [comment]
To reproduce run any previously centered (and hardened) volume through the 3DCT / Seq 3D & 4DCT pipelines

**Comment by amymmorton** [comment]
since this projection branch is depreciated in favor of #99 - suggest closing
