### ISSUE TITLE
Remove promt - PartialVolume Generation : VRG

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#124]
depreciated.

![image](https://github.com/user-attachments/assets/7bb57f17-96d8-4ce0-959e-bbd9ff65fde5)

Please remove ui popup when partial volume button click

**Comment by jcfr** [comment]
The prompt was originally introduced through https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/108, @amymmorton do you know in which pull request the dialog became obsolete ?

**Comment by amymmorton** [comment]
The #121 was the new direction- but we are still unable to progess successfully

(the functionality in this issue was part of projective VRG generation. The analysis of this accuracy was performed internally again #110   The resultant 2d-3d results for first metacarpal and trapezium were poor and the usability in 4dct  prompted us to go the 3d-3d route)
