### ISSUE TITLE
Partial Volumes Generated do not spatially align with VolumeNode Input

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#125]
As seen with Cesar's data .. I tried a 3d static ct acquired by Dr Lalon'es group:

spatial mismatch of generated tfm/tiffs:

![image](https://github.com/user-attachments/assets/0538451f-2fd5-493d-97b2-6de4f077e899)
[
nrrd and seg](https://drive.google.com/drive/folders/1tKUCpprp3ggGn3VA_7d9q0YEdLrTa1bw?usp=drive_link)

**Comment by amymmorton** [comment]
for ref: this is a bilateral hand/wrist  ct scan, proper seg:

![image](https://github.com/user-attachments/assets/a90eee69-8e23-4e2e-8ffd-0fbd7d40e774)

**Comment by amymmorton** [comment]
All tforms are faulty!! I'm suppose top demo today - I checked the WRIST and it's wrong- 

![image](https://github.com/user-attachments/assets/3921ecf6-f0b0-4f9a-b31e-fa20c25b3cae)

**Comment by jcfr** [comment]
Thanks for feedback, looks our testing didn't account for this dataset and/or usecase. 

We should work together to identify which changes introduced the regression.

For reference, here are the recent SlicerAutoscoperM changes:

<img width="1382" alt="image" src="https://github.com/user-attachments/assets/cd185ba9-27af-4b17-8c71-273c0d944346">

**Comment by amymmorton** [comment]
IN regards to [this data](https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/125#issue-2603656125)

loaded from [nrrd and seg](https://drive.google.com/drive/folders/1tKUCpprp3ggGn3VA_7d9q0YEdLrTa1bw?usp=drive_link)

IN slicer/slicer@c6b01db correct PV formed. 

sourcebuild lib zip in Gdrive link as well

**Comment by amymmorton** [comment]
| dataset (sid) | segmentation type| link| align screenshot|
|--------|--------|--------|--------|
| WRIST BVR (WN00112) | STL Model | [link ](https://drive.google.com/file/d/1gn1Or-2A1QRt5607YArpPr5JwwP3KmoG/view?usp=drive_link )| ![image](https://github.com/user-attachments/assets/39ae606c-4fee-4fff-974f-56667f5e42a4)|
| THUMB 3DCT (BN00124)| STL Model| [link](https://drive.google.com/file/d/14dLK307oG974zeKsuA2J2YQWB6nvwJ3n/view?usp=drive_link)| ![image](https://github.com/user-attachments/assets/7812e793-abd6-4a23-8db0-946a6b02673c)|
| KNEE BVR (CXBM15)| STL Model| [link](https://drive.google.com/file/d/1sO5AO9k4b9S2hyJNXl71GtobdOfNnqAu/view?usp=drive_link)| ![image](https://github.com/user-attachments/assets/ff8ba705-3958-4a10-b115-a9c3bad709d1)|
| BILATERL HAND CT| STL Model| [link](https://drive.google.com/drive/folders/1tKUCpprp3ggGn3VA_7d9q0YEdLrTa1bw?usp=drive_link)| 
![image](https://github.com/user-attachments/assets/01c1d4a9-182e-4fd4-8464-f99fca4e6ece)|

**Comment by sbelsk** [comment]
Reopening as #128 didn't resolve the problem, but fixed a related bug.

**Comment by amymmorton** [comment]
Tue Nov 12 2024  (Revision: 34fa24c)
WRIST BVR (WN00112)  [link ](https://drive.google.com/file/d/1gn1Or-2A1QRt5607YArpPr5JwwP3KmoG/view?usp=drive_link )

Al PV correct *EXCEPT* the cropped volume node use case(last)



| segmentation type| align screenshot|
|--------|--------|
|  STL Model | ![image](https://github.com/user-attachments/assets/38b4cb87-3765-49cb-b92c-8633367370b9)  ![image](https://github.com/user-attachments/assets/c966abc0-3c49-4d50-bf83-e552dba01ba8)|
| Auto Seg|  ![image](https://github.com/user-attachments/assets/10ffc893-f58b-4df9-8b57-db890bfe1641) |
| Auto Seg (from crop roi, Partial V original neutral)| ![image](https://github.com/user-attachments/assets/bda6ba43-c32c-46cd-8490-65eaac314794)  |
| Auto Seg (from crop roi, Partial V CROP neutral)| ![image](https://github.com/user-attachments/assets/efa46b7e-f4a2-4f28-ba8f-f1f6be81d38b)  |

**Comment by amymmorton** [comment]
Tue Nov 12 2024 (Revision: https://github.com/BrownBiomechanics/SlicerAutoscoperM/commit/34fa24cd66f0b3402a1e8ea09cacef4b862e40a1)

BILATERL HAND CT 

Import to dicom db from file (rather than previously saved .nrrd)
![image](https://github.com/user-attachments/assets/f61752e6-23d0-4e6b-9bf1-4c4f314a6be0)



|  segmentation type| align screenshot|
|--------|--------|
|  auto seg|  ![image](https://github.com/user-attachments/assets/d6b2904f-d950-44c4-9b26-60c01b9e3211)
|

**Comment by amymmorton** [comment]
@jcfr 

Could the issue be with the IJK - RAS (LPS) differences:

WRIST: (successful)
![image](https://github.com/user-attachments/assets/8859c09c-71aa-4db3-a828-b7cfe85a22cc)


BILATERAL: (fail) ![image](https://github.com/user-attachments/assets/f61752e6-23d0-4e6b-9bf1-4c4f314a6be0)

**Comment by amymmorton** [comment]
MUST BE! 

When the only diff between original and cropped as well!
![image](https://github.com/user-attachments/assets/19ff0bf2-01b2-4708-9aae-07768fb764ea)

![image](https://github.com/user-attachments/assets/1f7f67aa-47f4-4cf6-82bb-030986f9d8c8)

**Comment by sbelsk** [comment]
Excellent find, thanks for looking into it! I opened https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/147, which should fix the problem.
