### ISSUE TITLE
Improve PreProcessing workflow to support BVR cfg generation

### ISSUE THREAD

**Issue by jcfr** [BrownBiomechanics/SlicerAutoscoperM#131]
See https://autoscoper.readthedocs.io/en/latest/file-specifications/config.html

**Comment by jdholt04** [comment]
For us, the most useful UI to generate a config file would have inputs controls to identify Calibration, Radiograph, and Volume subdirectories, Optimization Offsets (already present), Volume Flip (already present), Render Resolution (2 number input boxes), and Voxel Size (3 number input boxes). Calibration files, folders containing radiographs, and volume files would be parsed from the subdirectories (this assumes that calibration files and radiograph image folders have a camera identifier in their filename). The information from the input controls would be compiled into a .cfg file (Version 1.1).


For reference, here is the current Generate Config tab:

![Picture1](https://github.com/user-attachments/assets/066a0a25-7217-4758-bb47-884b8902d8ec)

**Comment by amymmorton** [comment]
The advanced Options tab may be modified to meet some of these needs along with a more comprehensive Generate Config  drop down

![image](https://github.com/user-attachments/assets/c4f411f9-aa4e-403c-a4c8-fbd0ea5a35dc)

For reference, the folder explorer to the right shows the subdirectories typically found within the RadiographImages folder and the maycam files found in Calibration folder. (John - could you please add a screen shot from your projects too?)


Trial Name in General Input tab currently is a manual fill in... options for batch generation.. can't make too many file structure or naming restricitons

**Comment by jdholt04** [comment]
Here is a screenshot of the file structure for our project: 

![Capture](https://github.com/user-attachments/assets/97496ed4-3986-490d-af31-6e79de269d22)

On the left: Trial directory, what we would set as our Output Directory, and where we would want to save a .cfg

On the right: Contents of RadiographImages, Calibration, and Volumes subdirectories

**Comment by amymmorton** [comment]
@sbelsk do you have enough info to make a start on this - or do we need to do a quick show and tell? @jdholt04

**Comment by sbelsk** [comment]
That makes sense. A few more questions, to clarify:
 
 > volume files would be parsed from the subdirectories

Do we want to automatically load _all_ volume files found in the specified volume subdirectory? Should we assume that the volume flip and voxel size properties are set once and they apply to all volumes files found?
 
 > Calibration files, folders containing radiographs [...] would be parsed from the subdirectories (this assumes that calibration files and radiograph image folders have a camera identifier in their filename)

Matching up the radiographs to their camera calibration files might be difficult in general if we don't require a certain name format/convention or if we don't tell SAM what exact name to look for. What are your thoughts on this?

**Comment by amymmorton** [comment]
q1. Do we want to automatically load all volume files found in the specified volume subdirectory? 
a1. No- I think we want to create a 'session' so to speak for the user. Using the preprocessing module- the affiliated segmentation node volumes linked in the partial volume gen should be used for the 'session'.

q2.Should we assume that the volume flip and voxel size properties are set once and they apply to all volumes files found?
a2. voxel size is set from the volume node referenced in the partial volume generation- so those value should be inherited and used for that 'session'. Keep volume flip manually adjustable (but yes all volumes are considered children of the same parent and should have the same vol flip vlaues)

**Comment by amymmorton** [comment]
suggest #133 as step forward for this and #125

**Comment by amymmorton** [comment]
@sbelsk suggest relocating trial name in the General Input ui drop down into the Generate Config group
