### ISSUE TITLE
Remove obsolete collapsible group box related "VRG generation"

### ISSUE THREAD

**Issue by jcfr** [BrownBiomechanics/SlicerAutoscoperM#132]
Suggested by @amymmorton

**Comment by sbelsk** [comment]
Do we want to completely remove this feature along with any associated backend code, or just hide the collapsible UI group for now?

**Comment by amymmorton** [comment]
Good question- I'd say the feature may still be useful in other applications. Let's just hide the ui for now?

**Comment by amymmorton** [comment]
as suggested by @jcfr ... linking the VRG gen code to the[ EOS test BED](https://github.com/BrownBiomechanics/EOS-Test-Bed) and remove from here
