### ISSUE TITLE
Ankle Sample Data Filter 

### ISSUE THREAD

**Issue by kaitohl** [BrownBiomechanics/SlicerAutoscoperM#30]
Based on the ankle sample data @amymmorton showed me, the images may be over-filtered. I've attached the text for the .vie file our lab uses for ankle data. 

RadFilters_begin
SobelFilter_begin
Scale 0.5
Blend 2.1
SobelFilter_end
ContrastFilter_begin
Alpha 3.9
Beta 2.7
ContrastFilter_end
RadFilters_end
DrrRenderer_begin
SampleDistance 0.62
RayIntensity 0.49
Cutoff 0
DrrRenderer_end
DrrFilters_begin
SobelFilter_begin
Scale 0.53
Blend 2
SobelFilter_end
ContrastFilter_begin
Alpha 0.5
Beta 1
ContrastFilter_end
DrrFilters_end

![d](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/111300688/f51b8f89-4dce-4454-af77-04e06314179c)

**Comment by NicerNewerCar** [comment]
The filter will be updated, when I add the ground truth data for #32.
