### ISSUE TITLE
Extended frames - Sample data Wrist, Knee

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#38]
Using [extended dataset for the wrist/knee](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/extendedSampleData)

**WRIST**
Do we include the tra files? 
see https://github.com/BrownBiomechanics/Autoscoper/issues/149
correct this then add this data to Slicer index?

**KNEE**
Knee data is "full dicom"  tiff (not cropped)
Do we upload as is or crop

@amymmorton and @jdholt04  to upload :

- [x] PRE DICOM data 
- [x] wrl/stl export

**Comment by NicerNewerCar** [comment]
> Do we include the tra files?

Yes, the sample data will need some ground truth data for #32

**Comment by amymmorton** [comment]
[Pre release v.1.4.](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/extendedSampleData)
