### ISSUE TITLE
OpenCL OpenGL Error -1000

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/SlicerAutoscoperM#57]
In #56 I saw that @jdholt04 was getting a `-1000 Unknown` error [during the creation](https://github.com/BrownBiomechanics/Autoscoper/blob/75eb9ad5ac1ab490b1bb1f8e0f97bd60d86f8a99/libautoscoper/src/gpu/opencl/OpenCL.cpp#L597-L708) of the OpenCL-OpenGL context.

According to [this site](https://streamhpc.com/blog/2013-04-28/opencl-error-codes/) (and confirmed by the [OpenCL 1.0 specs](https://registry.khronos.org/OpenCL/specs/opencl-1.0.pdf#page=270)) `-1000` corresponds to a `CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR`.

However, I was unable to find a reference to `CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR` in the [OpenCL 1.2 spec](https://registry.khronos.org/OpenCL/specs/opencl-1.2.pdf), this is the minimum version required by Autoscoper. 

Could you provide hardware and driver specs for your machine?

Ideally:
* Make/Model GPU
* Make/Model CPU
* GPU driver version 

### Other Resources

https://stackoverflow.com/questions/42709957/determining-the-exact-cause-of-cl-invalid-gl-sharegroup-reference-khr

**Comment by jdholt04** [comment]
Here are the hardware and driver specs:

GPU: Intel UHD Graphics 770, Driver Version: 30.0.101.1002

GPU: NVIDIA GeForce RTX 3070, Driver Version: 31.0.15.1694

CPU: 12th Gen Intel Core i9-12900K

**Comment by NicerNewerCar** [comment]
I do see your Nvidia driver is out of date `516.94` vs. the [latest from Nvidia](https://www.nvidia.com/download/driverResults.aspx/211709/en-us/) `537.42`.

If you could update your driver and then try again, hopefully, that would fix it.

If not then maybe OpenCL/OpenGL are being split between the integrated GPU and the dedicated GPU?

**Comment by jcfr** [comment]
@jdholt04 Could you try setting the `__NV_PRIME_RENDER_OFFLOAD` and `__GLX_VENDOR_LIBRARY_NAME` environment variables before starting Slicer ?

For example:

```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia ./Slicer
```

References:
* https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html

**Comment by jdholt04** [comment]
@NicerNewerCar @NicerNewerCar I have updated the Nvidia driver and still received the error, so I set the __NV_PRIME_RENDER_OFFLOAD and __GLX_VENDOR_LIBRARY_NAME environment variables before starting Slicer and still received the error.  I was using an older preview release of 3D slicer, so I downloaded the most recent release and still receive the error.

**Comment by jdholt04** [comment]
My computer was un plugged and moved for carpet cleaning over the weekend, and I just thought to check to make sure I put the display cables in the correct ports and that seems to have been the issue as I am no longer having any errors. Thank you for taking the time to help, and I apologize for not checking that sooner.

![SAM](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/138158777/0d8e1d1a-fd7e-442d-911f-498b2e0b4c6a)

**Comment by NicerNewerCar** [comment]
No worries, glad this is working now!
