### ISSUE TITLE
VRG- output tiff not associated with trial name

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#61]
For #53 

Especially if wanting to consruct multiple series .. trial name field should name-associate with Trial Name field
![vrg_trialNames](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/65ca790a-efb3-4c2f-b17a-6057123dc5cc)

**Comment by amymmorton** [comment]
problematic when attempting to do multiple volumes in a series- overwrites the tifc name in a camera folder

**Comment by NicerNewerCar** [comment]
As part of the #58 (4DCT) frames are labeled from `{frameNum}.tiff`.

I can update the frames to have a name like `{frameNum}-{volumeName}.tiff`.
