### ISSUE TITLE
apply .tfm of partial volumes on launch

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#93]
- create in Transforms folder with .tra - associated tfm of all partial volumes

**Comment by NicerNewerCar** [comment]
Quick clarification: This is asking for (during PV generation) to create an Autoscoper TRA file with the `Origin2DICOM` transform. So when the trial is loaded into Autoscoper those tracking files are automatically loaded. As a quick way to verify they are in the right place?

**Comment by amymmorton** [comment]
I don't think so.. we need to combine both- such that the resultant tra places each bone into the same space as was segemented. 

Say 'frame 0" of the sequence was a duplicate of the neutral (from which PV were extracted) 

The tra would transform each PV to a match of frame0

I believe tis takes both Origin2DICOM and each rigid body tfm into account
